language: python

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      language: generic
      env: PYTHON="python3" PACKAGES="python3-gi python3-gi-cairo python3-nose"

install:
 - sudo apt-get update -q
 - sudo apt-get install --no-install-recommends -y gir1.2-notify-0.7 gir1.2-gtk-3.0 gir1.2-appindicator3 $(echo $PACKAGES)
 - virtualenv --python=$PYTHON --system-site-packages _venv
 - source _venv/bin/activate
 - pip install -r requirements.txt
 - pip3 install codecov
 - sudo python3 setup.py install

script: python3 -m "nose" --with-coverage --cover-package=furikura

after_success:
  - bash <(curl -s https://codecov.io/bash)
